name: create a comment on new issue
# run only when we have the issue
on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: windows
    steps:
      # to make a comment on newly create issue we have the requirement of the issue
      - name: "dump github context"
        run:  echo '$ {{ toJSON(github.event) }}' | jq
        shell: cmd
        # to comment on any of the above issue
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: '$ {{ (github.event.issue.number) }}'
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
          
  comment-with-api:
      runs-on: windows
      steps:
        -name: create comment with API
          run: 
            gh api -X POST \
              http://api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issue/${ISSUE_NUMBER/comments \
              -f body= '
              comment but from the API call not action
            '
          env: # only available for the duration of this workflow
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ORGANIZATION: ${{github.event.organisation.login }}
            REPOSITORY: ${{ github.event.repository.name }}
            ISSUE_NUMBER: ${{github.event.issue.number }}
          
